-- AUTO-GENERATED by scripts/utils/sql-generators.py
-- source: as-01-source-schema
-- Do not hand-edit; edit the schema JSON and regenerate instead.

CREATE TABLE IF NOT EXISTS "src_transaction_daily" (
    "transaction_id" TEXT NOT NULL,
    "account_id" TEXT,
    "transaction_date" DATE,
    "posting_date" DATE,
    "transaction_type" TEXT,
    "currency_code" VARCHAR(3),
    "transaction_amount" NUMERIC(18,2),
    "local_currency_amount" NUMERIC(18,2),
    "exchange_rate" NUMERIC(18,8),
    "branch_code" TEXT,
    "product_code" TEXT,
    "source_system" TEXT,
    "ingestion_file" TEXT,
    "source_extract_ts" TIMESTAMPTZ
);
