-- AUTO-GENERATED by scripts/utils/sql-generators.py
-- source: as-02-gl-balance-schema
-- Do not hand-edit; edit the schema JSON and regenerate instead.

CREATE SCHEMA IF NOT EXISTS "finance";

CREATE TABLE IF NOT EXISTS "finance"."gl_balance" (
    "accounting_date" DATE NOT NULL,
    "legal_entity" TEXT NOT NULL,
    "gl_account" TEXT NOT NULL,
    "cost_center" TEXT NOT NULL,
    "currency" VARCHAR(3) NOT NULL,
    "opening_balance" NUMERIC(20,2) NOT NULL,
    "debit_movement" NUMERIC(20,2) NOT NULL,
    "credit_movement" NUMERIC(20,2) NOT NULL,
    "closing_balance" NUMERIC(20,2) NOT NULL,
    PRIMARY KEY ("accounting_date", "legal_entity", "gl_account", "cost_center", "currency")
);
