-- AUTO-GENERATED by scripts/utils/sql-generators.py
-- source: as-02-accounting-mapping-schema
-- Do not hand-edit; edit the schema JSON and regenerate instead.

CREATE SCHEMA IF NOT EXISTS "ref";

CREATE TABLE IF NOT EXISTS "ref"."accounting_mapping" (
    "product_code" TEXT NOT NULL,
    "transaction_type" TEXT NOT NULL CHECK ("transaction_type" IN ('DEBIT', 'CREDIT')),
    "expected_gl_account" TEXT NOT NULL,
    "expected_cost_center" TEXT NOT NULL,
    "effective_start_date" DATE NOT NULL,
    "effective_end_date" DATE,
    PRIMARY KEY ("product_code", "transaction_type", "effective_start_date")
);
