-- AUTO-GENERATED by scripts/utils/sql-generators.py
-- source: as-02-finance-transactions-schema
-- Do not hand-edit; edit the schema JSON and regenerate instead.

CREATE SCHEMA IF NOT EXISTS "bronze";

CREATE TABLE IF NOT EXISTS "bronze"."finance_transactions" (
    "transaction_id" TEXT NOT NULL,
    "account_id" TEXT NOT NULL,
    "transaction_date" DATE NOT NULL,
    "posting_date" DATE NOT NULL,
    "transaction_amount" NUMERIC(18,2) NOT NULL,
    "currency" VARCHAR(3) NOT NULL,
    "exchange_rate" NUMERIC(18,8) NOT NULL,
    "local_amount" NUMERIC(18,2) NOT NULL,
    "debit_credit_indicator" TEXT NOT NULL CHECK ("debit_credit_indicator" IN ('DEBIT', 'CREDIT')),
    "product_code" TEXT NOT NULL,
    "branch_code" TEXT NOT NULL,
    "gl_account" TEXT NOT NULL,
    "cost_center" TEXT NOT NULL,
    "legal_entity" TEXT NOT NULL,
    PRIMARY KEY ("transaction_id")
);
