-- AUTO-GENERATED by scripts/utils/sql-generators.py
-- source: as-03-payment-reporting-schema
-- Do not hand-edit; edit the schema JSON and regenerate instead.

CREATE SCHEMA IF NOT EXISTS "regulatory";

CREATE TABLE IF NOT EXISTS "regulatory"."payment_reporting" (
    "reporting_date" DATE NOT NULL,
    "customer_id" TEXT NOT NULL,
    "payment_type" TEXT NOT NULL,
    "domestic_crossborder_flag" TEXT NOT NULL CHECK ("domestic_crossborder_flag" IN ('DOMESTIC', 'CROSSBORDER')),
    "transaction_count" NUMERIC(12,0) NOT NULL,
    "total_transaction_amount" NUMERIC(20,2) NOT NULL,
    "reporting_currency" VARCHAR(3) NOT NULL,
    "legal_entity" TEXT NOT NULL,
    PRIMARY KEY ("reporting_date", "customer_id", "payment_type", "legal_entity", "domestic_crossborder_flag")
);
