-- AUTO-GENERATED by scripts/utils/sql-generators.py
-- source: as-03-customer-master-schema
-- Do not hand-edit; edit the schema JSON and regenerate instead.

CREATE SCHEMA IF NOT EXISTS "bronze";

CREATE TABLE IF NOT EXISTS "bronze"."customer_master" (
    "customer_id" TEXT NOT NULL,
    "customer_type" TEXT NOT NULL CHECK ("customer_type" IN ('INDIVIDUAL', 'CORPORATE')),
    "residence_country" VARCHAR(2) NOT NULL,
    "risk_rating" TEXT NOT NULL CHECK ("risk_rating" IN ('LOW', 'MEDIUM', 'HIGH')),
    "segment" TEXT NOT NULL CHECK ("segment" IN ('RETAIL', 'PRIVATE', 'CORPORATE', 'SME')),
    "legal_entity" TEXT NOT NULL,
    "effective_start_date" DATE NOT NULL,
    "effective_end_date" DATE,
    PRIMARY KEY ("customer_id", "effective_start_date")
);
