-- AUTO-GENERATED by scripts/utils/sql-generators.py
-- source: as-03-payment-transactions-schema
-- Do not hand-edit; edit the schema JSON and regenerate instead.

CREATE SCHEMA IF NOT EXISTS "source";

CREATE TABLE IF NOT EXISTS "source"."payment_transactions" (
    "payment_id" TEXT NOT NULL,
    "customer_id" TEXT,
    "account_id" TEXT,
    "payment_date" DATE,
    "payment_timestamp" TIMESTAMPTZ,
    "payment_type" TEXT,
    "payment_channel" TEXT,
    "beneficiary_country" VARCHAR(2),
    "currency" VARCHAR(3),
    "amount" NUMERIC(18,2),
    "status" TEXT,
    "legal_entity" TEXT
);
