-- AUTO-GENERATED by scripts/utils/sql-generators.py
-- source: rc-audit-trail-schema
-- Do not hand-edit; edit the schema JSON and regenerate instead.

CREATE SCHEMA IF NOT EXISTS "reconciliation";

CREATE TABLE IF NOT EXISTS "reconciliation"."rc_audit_trail" (
    "audit_id" SERIAL NOT NULL,
    "batch_id" INTEGER NOT NULL,
    "action" TEXT NOT NULL CHECK ("action" IN ('NOTIFY', 'INVESTIGATE')),
    "actor" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("audit_id"),
    FOREIGN KEY ("batch_id") REFERENCES "reconciliation"."rc_batch_control" ("batch_id")
);
