-- AUTO-GENERATED by scripts/utils/sql-generators.py
-- source: rc-batch-control-schema
-- Do not hand-edit; edit the schema JSON and regenerate instead.

CREATE SCHEMA IF NOT EXISTS "reconciliation";

CREATE TABLE IF NOT EXISTS "reconciliation"."rc_batch_control" (
    "batch_id" SERIAL NOT NULL,
    "batch_date" DATE NOT NULL,
    "assessment_id" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'RUNNING' CHECK ("status" IN ('RUNNING', 'PASS', 'WARNING', 'FAIL')),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("batch_id")
);
