#!/usr/bin/env python3
"""sql-generators.py

Reads a source schema JSON (single source of truth) and generates the
corresponding PostgreSQL CREATE TABLE DDL.

Stateless / deterministic: overwriting its own output is safe, and the
emitted DDL uses `CREATE TABLE IF NOT EXISTS` so applying it is rerun-safe.

See docs/features/02-dev-env-setup-postgresql-db.md -> Design -> schemas
for the json-type -> postgres-type mapping this implements, and
docs/features/04-seed-mock-data.md -> Design for the multi-schema /
composite-key / enforce_constraints extensions.

Usage (single file, feature 02's original interface):
    python3 scripts/utils/sql-generators.py \
        --schema data/schemas/as01-source-schema.json \
        --out postgresql/as01-source-create-table.sql

Usage (batch, feature 04):
    python3 scripts/utils/sql-generators.py \
        --schema-dir data/schemas --out-dir postgresql
"""

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SCHEMA = REPO_ROOT / "data" / "schemas" / "as01-source-schema.json"
DEFAULT_OUT = REPO_ROOT / "postgresql" / "as01-source-create-table.sql"


def pg_type(column: dict) -> str:
    """Map a schema-json column definition to a PostgreSQL column type."""
    json_type = column["type"]

    if json_type == "string":
        length = column.get("length")
        return f"VARCHAR({length})" if length else "TEXT"
    if json_type == "date":
        return "DATE"
    if json_type == "timestamp":
        return "TIMESTAMPTZ"
    if json_type == "decimal":
        precision = column.get("precision")
        scale = column.get("scale")
        if precision is None or scale is None:
            raise ValueError(
                f"column '{column['name']}': type 'decimal' requires "
                "'precision' and 'scale'"
            )
        return f"NUMERIC({precision},{scale})"

    raise ValueError(f"column '{column['name']}': unsupported json type '{json_type}'")


def qualify_table_name(table_name: str) -> tuple[str | None, str]:
    """Split a possibly schema-qualified table_name into (schema, table).

    'bronze.transaction_daily' -> ('bronze', 'transaction_daily')
    'src_transaction_daily'    -> (None, 'src_transaction_daily')  # public, unqualified
    """
    if "." in table_name:
        schema, table = table_name.split(".", 1)
        return schema, table
    return None, table_name


def column_ddl(column: dict, business_key: list, enforce_constraints: bool) -> str:
    parts = [f'    "{column["name"]}" {pg_type(column)}']

    not_null = not column.get("nullable", True)
    if not enforce_constraints:
        # Relaxed raw-landing table: only a business-key column stays NOT NULL
        # (an unidentifiable row isn't a data-quality finding, it's unusable) -
        # every other NOT NULL / CHECK constraint is dropped so dirty rows the
        # profiling exercise is meant to find are actually insertable. See
        # docs/features/04-seed-mock-data.md -> constraint relaxation.
        not_null = column["name"] in business_key

    if not_null:
        parts.append("NOT NULL")

    if enforce_constraints and (allowed := column.get("allowed_values")):
        values_sql = ", ".join(f"'{v}'" for v in allowed)
        parts.append(f'CHECK ("{column["name"]}" IN ({values_sql}))')

    return " ".join(parts)


def generate_table_ddl(table: dict) -> str:
    business_key = table.get("business_key", [])
    enforce_constraints = table.get("enforce_constraints", True)
    schema, table_name = qualify_table_name(table["table_name"])
    qualified = f'"{schema}"."{table_name}"' if schema else f'"{table_name}"'

    lines = [column_ddl(col, business_key, enforce_constraints) for col in table["columns"]]

    # Composite (or single-column) primary key as one trailing table-level
    # constraint, rather than per-column PRIMARY KEY, so multi-column business
    # keys (e.g. finance.gl_balance) emit valid SQL. Only emitted when this
    # table enforces constraints - relaxed landing tables keep business_key as
    # metadata only (see column_ddl above).
    if enforce_constraints and business_key:
        quoted_key = ", ".join(f'"{col}"' for col in business_key)
        lines.append(f"    PRIMARY KEY ({quoted_key})")

    columns_sql = ",\n".join(lines)
    ddl = ""
    if schema:
        ddl += f'CREATE SCHEMA IF NOT EXISTS "{schema}";\n\n'
    ddl += f"CREATE TABLE IF NOT EXISTS {qualified} (\n{columns_sql}\n);"
    return ddl


def generate_sql(schema: dict) -> str:
    header = (
        "-- AUTO-GENERATED by scripts/utils/sql-generators.py\n"
        f"-- source: {schema.get('schema_id', 'unknown schema')}\n"
        "-- Do not hand-edit; edit the schema JSON and regenerate instead.\n\n"
    )
    tables_sql = "\n\n".join(generate_table_ddl(t) for t in schema["tables"])
    return header + tables_sql + "\n"


def output_path_for(schema_path: Path, out_dir: Path) -> Path:
    """as01-bronze-schema.json -> postgresql/as01-bronze-create-table.sql"""
    stem = schema_path.stem
    if stem.endswith("-schema"):
        stem = stem[: -len("-schema")]
    return out_dir / f"{stem}-create-table.sql"


def generate_one(schema_path: Path, out_path: Path) -> list[str]:
    schema = json.loads(schema_path.read_text())
    sql = generate_sql(schema)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(sql)
    return [t["table_name"] for t in schema["tables"]]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--schema", type=Path, default=None, help="single schema JSON file")
    parser.add_argument("--out", type=Path, default=None, help="single output SQL file")
    parser.add_argument("--schema-dir", type=Path, default=None, help="directory of schema JSON files (batch mode)")
    parser.add_argument("--out-dir", type=Path, default=None, help="directory to write generated SQL files (batch mode)")
    args = parser.parse_args()

    batch_mode = args.schema_dir is not None or args.out_dir is not None
    if batch_mode and (args.schema_dir is None or args.out_dir is None):
        print("[FAIL] sql-generators: --schema-dir and --out-dir must be given together", file=sys.stderr)
        return 1

    try:
        if batch_mode:
            schema_files = sorted(args.schema_dir.glob("*.json"))
            if not schema_files:
                raise ValueError(f"no *.json schema files found in {args.schema_dir}")
            all_tables: list[str] = []
            for schema_path in schema_files:
                out_path = output_path_for(schema_path, args.out_dir)
                tables = generate_one(schema_path, out_path)
                all_tables.extend(tables)
                print(f"[PASS] {schema_path.name} -> {out_path}: {', '.join(tables)}")
            print(f"[PASS] generated DDL for {len(all_tables)} table(s) from {len(schema_files)} schema file(s)")
        else:
            schema_path = args.schema or DEFAULT_SCHEMA
            out_path = args.out or DEFAULT_OUT
            tables = generate_one(schema_path, out_path)
            print(f"[PASS] generated DDL for table(s): {', '.join(tables)}")
            print(f"[PASS] wrote {out_path.relative_to(REPO_ROOT) if out_path.is_relative_to(REPO_ROOT) else out_path}")
    except Exception as exc:  # noqa: BLE001 - top-level safe wrapper, no silent failure
        print(f"[FAIL] sql-generators: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
